# Generated by Django 4.1.2 on 2022-10-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_desciption_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.CharField(default='Insert Image', max_length=255),
            preserve_default=False,
        ),
    ]
